---
config:
  layout: dagre
  theme: redux-color
  themeVariables:
    fontSize: "15px"
    primaryColor: "#dbeafe"
    primaryBorderColor: "#1d4ed8"
    primaryTextColor: "#000000ff"
    lineColor: "#000000ff"
    edgeLabelBackground: "#ffffff"
    attributeBackgroundColorOdd: "#f8fafc"
    attributeBackgroundColorEven: "#e2e8f0"
---
erDiagram
	direction LR
	DRUG {
		string node_name  ""  
		float mol_weight  ""  
		float tpsa  ""  
		float clogp  ""  
		vector embedding_32d  ""  
	}

	DISEASE {
		string mondo_id  ""  
		string description  ""  
		vector embedding_32d  ""  
	}

	PROTEIN {

	}

	DRUG||--o{DISEASE:"treats"
	DRUG||--o{PROTEIN:"interacts_with"
	DISEASE||--o{PROTEIN:"associated_with"
	PROTEIN||--o{DRUG:"binds_to"
